input {
  gelf {
    port => 12201
  }
}

filter {
  mutate {
    rename => { "host" => "docker_container_name" }
    add_field => { "app_name" => "%{[docker_container_name]}" }
  }
}

output {
  elasticsearch {
    hosts => ["elasticsearch:9200"]
    index => "docker-logs-%{+YYYY.MM.dd}"
  }
}
